In [5]:
import numpy as np 
import pandas as pd

In [6]:
food1 = pd.read_csv('/Users/ahana/FoodieFinder/food_csv/food1.csv')
food_2 = pd.read_csv('/Users/ahana/FoodieFinder/food_csv/food_2.csv')

In [7]:
food1.head(1)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East

In [8]:
food_2.head(1)

,Unnamed: 0,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region,img_url
0,NaN,Adhirasam,"Rice flour, jaggery, ghee, vegetable oil, elachi",vegetarian,10,50,sweet,dessert,West Bengal,East,https://www.crazymasalafood.com/wp-content/ima...

In [9]:
food_2 = food_2.drop(columns=["Unnamed: 0"])

In [10]:
food = pd.concat([food1, food_2], ignore_index=True)

In [11]:
food.head(4)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region,img_url
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East,NaN
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West,NaN
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North,NaN
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West,NaN

In [12]:
food = food.drop_duplicates(subset="name")

In [13]:
food.head().shape

(5, 10)

In [14]:
food.isnull().sum()

name                0
ingredients         0
diet                0
prep_time           0
cook_time           0
flavor_profile      0
course              0
state               0
region              1
img_url           255
dtype: int64

In [15]:
food.dropna().shape

(1, 10)

In [16]:
food["food_id"] = range(1, len(food) + 1)

In [17]:
food=food[['food_id','name','diet','course','flavor_profile','state','img_url']]

In [18]:
food.head()

,food_id,name,diet,course,flavor_profile,state,img_url
0,1,Balu shahi,vegetarian,dessert,sweet,West Bengal,NaN
1,2,Boondi,vegetarian,dessert,sweet,Rajasthan,NaN
2,3,Gajar ka halwa,vegetarian,dessert,sweet,Punjab,NaN
3,4,Ghevar,vegetarian,dessert,sweet,Rajasthan,NaN
4,5,Gulab jamun,vegetarian,dessert,sweet,West Bengal,NaN

In [19]:
food['tags'] = food['flavor_profile'] + " " + food['course'] + " " + food['state']+ " " + food['diet']

In [20]:
new_df = food[['food_id','name','tags','img_url']]

In [21]:
new_df.head(2)

   food_id        name                                  tags img_url
0        1  Balu shahi  sweet dessert West Bengal vegetarian     NaN
1        2      Boondi    sweet dessert Rajasthan vegetarian     NaN

VECTORIZATION

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(food["tags"]).toarray()

In [24]:
similarity = cosine_similarity(vectors)

In [25]:
similarity.shape

(256, 256)

In [26]:
def recommend(food):

    food_idx = new_df[new_df['name'] == food].index[0]

    dist = similarity[food_idx]

    food_list = sorted(
        list(enumerate(dist)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in food_list:
        print(new_df.iloc[i[0]]['name'])

In [27]:
recommend('Dahi vada')

Poha
Chakali
Kombdi vade
Sabudana Khichadi
Surnoli

In [28]:
new_df.to_csv("new_df.csv", index=False)